#!/usr/bin/env python
try:
    from pyromaths import pyromaths
except ImportError:
    import sys, os.path
    basedir = os.path.dirname(os.path.realpath(__file__))
    sys.path.insert(0, os.path.join(basedir,'src'))
    from pyromaths import pyromaths
pyromaths.main()
