#!/usr/bin/env python

import sys
from os.path import dirname, join, realpath
from os import chdir

try:
    from pyromaths import pyromaths
except ImportError:
    basedir = dirname(realpath(__file__))
    workdir = join(basedir,'src')
    sys.path.insert(0, basedir)
    from src import pyromaths
    chdir(workdir)
pyromaths.main()
