#!/usr/bin/env python

"""Pyromaths exercise regression tests

To display help:

> testexo --help
"""

import argparse
import sys
import unittest

import pyromaths.ex.test

VERSION = "0.1.0"

def match_exercise(path):
    """Return the exercises in `path`."""
    exercises = []
    for level in pyromaths.ex.levels:
        for exercise in pyromaths.ex.levels[level]:
            if pyromaths.ex.LegacyExercise in exercise.__bases__:
                continue
            if exercise.__module__.startswith(path):
                exercises.append(exercise)
    return exercises

def exercise_argument(string):
    """Return the exercises matching ``string``.

    :param str string: a string, option of one of `testexo` commands.
    :rtype: dict
    :return: A dictionary with exercises as keys, and sets of integers (seeds)
    as values.
    """
    splitted = string.split(":")
    if len(splitted) == 1:
        path = string
        seeds = []
    elif len(splitted) == 2:
        path, seeds = string.split(":")
        try:
            seeds = [int(seed) for seed in seeds.split(",")]
        except ValueError:
            raise argparse.ArgumentTypeError("TODO")
    else:
        raise argparse.ArgumentTypeError("TODO")

    if path.endswith(".py"):
        path = path[:-3]

    return dict([
        (exo, seeds) for exo in match_exercise(path.replace('/', '.'))
        ])

def argument_parser():
    """Return an argument parser"""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-v', '--version',
        action='version',
        version='%(prog)s {version}'.format(version=VERSION),
        )
    subparsers = parser.add_subparsers(title='Commands', dest='command')
    subparsers.required = True
    subparsers.dest = 'command'

    # Create
    create = subparsers.add_parser(
        'create',
        help='Create test given in argument. If not, create missing tests.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    create.add_argument(
        "exercise",
        metavar='EXERCISE[:SEED[,SEED]]',
        nargs='*', type=exercise_argument, default=None,
        help='Exercices to test. If empty, all exercises are tested.'
        )

    # Remove
    remove = subparsers.add_parser(
        'remove',
        help='Remove a test',
        )
    remove.add_argument(
        "exercise",
        metavar='EXERCISE[:SEED[,SEED]]',
        nargs='+', type=exercise_argument, default=None,
        help='Exercices to remove.',
        )

    # Update
    update = subparsers.add_parser(
        'update',
        help=(
            "Perform tests given in argument (if not, update all tests)."
            "Update tests that have changed."
            ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    update.add_argument(
        "exercise",
        metavar='EXERCISE[:SEED[,SEED]]',
        nargs='*', type=exercise_argument, default=None,
        help='Exercices to test. If empty, all exercises are tested.'
        )

    # Show
    show = subparsers.add_parser(
        'show',
        help='Compile and show some exercises.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    show.add_argument(
        "exercise",
        metavar='EXERCISE[:SEED[,SEED]]',
        nargs='*', type=exercise_argument, default=None,
        help='Exercices to show. If empty, all exercises are showed.'
        )

    # Check
    check = subparsers.add_parser(
        'check',
        help='Test exercises.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    check.add_argument(
        "exercise",
        metavar='EXERCISE[:SEED[,SEED]]',
        nargs='*', type=exercise_argument, default=None,
        help='Exercices to check. If empty, all exercises are checked.'
        )

    return parser

def do_create(exercises, test_suite):
    """Action for command line 'create'."""
    for exo in exercises:
        if not exercises[exo]:
            seeds = set([0])
        else:
            seeds = exercises[exo]
        for seed in seeds:
            if not test_suite.has_test(exo, seed):
                test_suite.create_test(exo, seed)
    test_suite.write_testfiles()

def do_remove(exercises, test_suite):
    """Action for command line 'remove'."""
    for exo in exercises:
        if not exercises[exo]:
            seeds = test_suite.get_exercise(exo).seeds
        else:
            seeds = exercises[exo]
        for seed in seeds:
            if test_suite.has_test(exo, seed):
                test_suite.remove_test(exo, seed)
    test_suite.write_testfiles()

def do_update(exercises, test_suite):
    """Action for command line 'update'."""
    for exo in exercises:
        if not exercises[exo]:
            seeds = test_suite.get_exercise(exo).seeds
        else:
            seeds = exercises[exo]
        for seed in seeds:
            if not pyromaths.ex.test.simple_runtest(
                    test_suite.get_exercise(exo)[seed]
                ):
                test_suite.create_test(exo, seed)
    test_suite.write_testfiles()

def do_show(exercises, test_suite):
    """Action for command line 'show'."""
    for exo in exercises:
        if not exercises[exo]:
            seeds = test_suite.get_exercise(exo).seeds
        else:
            seeds = exercises[exo]
        for seed in seeds:
            test_suite.get_exercise(exo)[seed].show()

def do_check(exercises, test_suite):
    """Run the tests"""
    suite = unittest.TestSuite(list(test_suite.iter_tests()))
    unittest.TextTestRunner(verbosity=2).run(suite)

COMMANDS = {
    "check": do_check,
    "create": do_create,
    "remove": do_remove,
    "show": do_show,
    "update": do_update,
    }

def main():
    """Main function"""
    pyromaths.ex.load()
    options = argument_parser().parse_args(sys.argv[1:])
    test_suite = pyromaths.ex.test.create_test_suite()

    exercises = {}
    for exo_option in options.exercise:
        for exo in exo_option:
            if exo not in exercises:
                exercises[exo] = set()
            exercises[exo] |= set(exo_option[exo])

    COMMANDS[options.command](exercises, test_suite)

if __name__ == "__main__":
    main()
